#!/usr/bin/env bash
set -euo pipefail

export PATH=/usr/lib/sdk/dotnet10/bin:$PATH
export RID=linux-$(echo "${FLATPAK_ARCH}" | sed 's/x86_64/x64/; s/aarch64/arm64/')

# Restore without an explicit RID first: restoring with `-r` hits a NuGet
# NullReferenceException inside the dotnet10 SDK (SDK 10.0.300). Publishing
# with --no-restore then uses the RID assets generated by the plain restore
# (RuntimeIdentifiers is declared in the project file).
dotnet restore Stratum.Desktop/Stratum.Desktop.csproj --source "$(pwd)/nuget-offline" -p:NuGetAudit=false -p:RuntimeFrameworkVersion=10.0.8

dotnet publish Stratum.Desktop/Stratum.Desktop.csproj -c Release -r "$RID" --self-contained true \
  -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true \
  --no-restore -p:NuGetAudit=false -p:RuntimeFrameworkVersion=10.0.8 -o /app/bin/

# Rename the single-file executable to the command name referenced by the manifest.
mv /app/bin/Stratum /app/bin/stratum

install -Dm644 packaging/flathub/org.stratumauth.Desktop.desktop \
  /app/share/applications/org.stratumauth.Desktop.desktop
install -Dm644 Stratum.Desktop/Resources/icon.png \
  /app/share/icons/hicolor/512x512/apps/org.stratumauth.Desktop.png
install -Dm644 packaging/flathub/org.stratumauth.Desktop.metainfo.xml \
  /app/share/metainfo/org.stratumauth.Desktop.metainfo.xml
